export default {
  DATAIMG1: require('../assets/images/CoolKidsHighTech.png'),
  DATAIMG2: require('../assets/images/CoolKidsAloneTime.png'),
  DATAIMG3: require('../assets/images/CoolKidsHighTech.png'),
  DATAIMG4: require('../assets/images/CoolKidsAloneTime.png'),
  DATAIMG5: require('../assets/images/CoolKidsHighTech.png'),
  // FACEBOOKIMG: require('../assets/images/Facebook.png'),
  INSTAGRAMIMG: require('../assets/images/Instagram.png'),
  GOOGLEIMG: require('../assets/images/Google.png'),
  LOGO1: require('../assets/images/Logo1.png'),
  GALLERY: require('../assets/images/gallery.png'),
  CAMERA: require('../assets/images/camera.png'),
  STUDENT: require('../assets/images/student.png'),
  UI_IMG: require('../assets/images/UI.jpg'),
  WEB_IMG: require('../assets/images/Web.jpg'),
  DATA_SCIENCE_IMG: require('../assets/images/DataScience.jpg'),
  GRAPHICS_IMG: require('../assets/images/Graphics.jpg'),
  PROGRAMING_IMG: require('../assets/images/Programing.jpg'),
};
