export default {
  INTROSCREEN1: 'IntroScreen1',
  INTROSCREEN2: 'IntroScreen2',
  INTROSCREEN3: 'IntroScreen3',
  LOGINSCREEN: 'LoginScreen',
  SIGNUPSCREEN: 'SignUpScreen',
  PROFILESCREEN: 'ProfileScreen',
  SETTINGSCREEN: 'SettingsScreen',
  HOMESCREEN: 'HOMesScreen',
  RESULTSCREEN: 'ResultScreen',
  PRODUCTSCREEN: 'ProductSceen',
  YOUR_COURSESSCREEN: 'YourCoursesScreen',
  CHOOSE_LESSONNSCREEN: 'ChooseLessonScreen',
  COURSE_LESSONSCREEN: 'CourseLessonScreen',
  COURSE_TESTSCREEN: 'CourseTestScreen',
  TEST_QUESTIONSCREEN: 'TestQuestionScreen',
  TEST_RESULTSCREEN: 'TestResultScreen',
  TABSCREENS: 'TabScreens',
  FORGOTSCREEN: 'ForgotScreen',
  COURSE_SAVED_SCREEN: 'CourseSavedScreen',
};
