export default {
  LOGINSCREEN: 'LoginScreen',
  SIGNUPSCREEN: 'SignUpScreen',
  PROFILESCREEN: 'ProfileScreen',
  SETTINGSCREEN: 'SettingsScreen',
  HOMESCREEN: 'HomeScreen',
  RESULTSCREEN: 'ResultScreen',
  PRODUCTSCREEN: 'ProductScreen',
  YOUR_COURSESSCREEN: 'YourCoursesScreen',
  CHOOSE_LESSONNSCREEN: 'ChooseLessonScreen',
  COURSE_LESSONSCREEN: 'CourseLessonScreen',
  COURSE_TESTSCREEN: 'CourseTestScreen',
  TABSCREENS: 'TabScreens',
  FORGOTSCREEN: 'ForgotScreen',
  COURSE_SAVED_SCREEN: 'CourseSavedScreen',
  SELECTED_COURSE_SCREEN: 'SelectedCourseScreen',
};
